name: scorers
channels:
  - conda-forge
  - rdkit/label/nightly
  - defaults
  - lich
dependencies:
  - python=3.7
  - rdkit
  - pip
  - syba
  - scikit-learn
  - pip:
    - git+https://github.com/reymond-group/RAscore.git